### PR TITLE
Apply style rules to source files.

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Description of changes:**

This PR contains **only** changes resulting from `make fmt`.

When this is merged, I will open a PR to ignore this commit from `git blame`, to keep the history ergonomic.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

After this change, `make fmt` results in no changes.

### CODE REVIEW

**Comment by cartermckinnon** [comment]
I did have to make one manual change, here: https://github.com/awslabs/amazon-eks-ami/pull/1076/files#diff-049390d14bc3ea2d7882ff0f108e2802ad9b043336c5fa637e93581d9a7fdfc2R145

The backslash (`\`) has different effect within backticks (\`) vs subshells (`$()`). The new style rules convert back-ticks to subshell syntax, because the latter is easier to read and is generally preferred to back-ticks because they're easier to nest -- each `$()` is an entirely new quoting context.

**Review by mmerkes — COMMENTED** [review]
Overall, LGTM. Thanks for cleaning house. I do have a couple of thoughts:

1. You should probably build an AMI and run the log collector script on a node to verify that nothing broke.
2. How will people know to run this as part of PRs? I don't see the README updated, or the PR instructions? Will test that this was run as part of the PR?

**Comment by cartermckinnon** [comment]
> You should probably build an AMI and run the log collector script on a node to verify that nothing broke.

Yeah, good call. I'll update with the outcome.

> How will people know to run this as part of PRs? I don't see the README updated, or the PR instructions? Will test that this was run as part of the PR?

I did update the contribution doc here: https://github.com/awslabs/amazon-eks-ami/blob/master/CONTRIBUTING.md?plain=1#L34

and #1068 will add a format check to the CI workflow.

**Comment by cartermckinnon** [comment]
I built a 1.23 AMI from this branch, created a nodegroup, then ran the log collector script like:
```
> curl -O https://raw.githubusercontent.com/awslabs/amazon-eks-ami/format-changes/log-collector-script/linux/eks-log-collector.sh
> chmod +x eks-log-collector.sh
> sudo ./eks-log-collector.sh

	This is version 0.7.2. New versions can be found at https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/

Trying to collect common operating system logs... 
Trying to collect kernel logs... 
Trying to collect mount points and volume information... 
Trying to collect SELinux status... 
Trying to collect iptables information... 
Trying to collect installed packages... 
Trying to collect active system services... 
Trying to Collect Containerd daemon information... 
Trying to Collect Containerd running information... 
Trying to Collect Docker daemon information... 
Trying to collect kubelet information... 
Trying to collect L-IPAMD introspection information... Trying to collect L-IPAMD prometheus metrics... Trying to collect L-IPAMD checkpoint... 
Trying to collect Multus logs if they exist... 
Trying to collect sysctls information... 
Trying to collect networking infomation... conntrack v1.4.4 (conntrack-tools): 244 flow entries have been shown.

Trying to collect CNI configuration information... 
Trying to collect Docker daemon logs... 
Trying to Collect sandbox-image daemon information... 
Trying to Collect CPU Throttled Process Information... 
Trying to Collect IO Throttled Process Information... 
Trying to archive gathered information... 

	Done... your bundled logs are located in /var/log/eks_i-0a681ff321eb876d4_2022-11-03_1840-UTC_0.7.2.tar.gz

```

**Review by mmerkes — APPROVED** [review]

**Pull request merged**
