### PR TITLE
templates: downgrade to containerd 1.7.11

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Issue #, if available:**

Mitigates #1933 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cartermckinnon** [comment]
Checked the version-info from the CI artifacts and LGTM:
```
        "containerd": "1.7.11-1.amzn2.0.1",
```
```
        "containerd": "1.7.11-1.amzn2023.0.1",
```

**Review by ndbaker1 — APPROVED** [review]
🚀

**Pull request merged**
