### PR TITLE
Removed ulimit reduction

### LINKED ISSUE #193: Latest AMI version lowers ulimit and breaks Elasticsearch
**What happened**:

Upgrading to the latest AMI _reduced_ the `ulimit` to 8192 which broke Elasticsearch deployments.  Elasticsearch requires a `ulimit` of 65536.

**What you expected to happen**:

Upgrading AMIs shouldn't reduce the `ulimit` (which is the opposite effect of what the PR #186 implies).

**How to reproduce it (as minimally and precisely as possible)**:

Use the latest AMI `amazon-eks-node-1.11-v20190220` - containers will have a max ulimit of 8192, not unlimited or 65536.

**Anything else we need to know?**:

This was broken by #186 - that PR _reduced_ the default limit, rather than increasing it.

**Environment**:
- AWS Region: `us-east-1`
- Instance Type(s): `m5.xlarge`
- AMI Version: `amazon-eks-node-1.11-v20190220`

### PR DESCRIPTION
**Pull request by micahhausler**
*Issue #, if available:*

Fixes #193
Reverts #186

*Description of changes:*

Revert ulimit reduction

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cpanato** [comment]
hello this change is applied in the current AMI for eks version 1.11 ? (ami-0eeeef929db40543c)

**Comment by lekspyl** [comment]
Hello,

looks like `amazon-eks-node-1.11-v20190220` is the latest AMI and it does not contain this patch.
Could you tell when is it expected for a new AMI to be released? Asking due to https://github.com/awslabs/amazon-eks-ami/issues/193 which I can't make to work on the current AMI version. If there is any working way to override max file descriptors value I will be more than thankful if you'll share it.

**Comment by dmarkey** [comment]
Hey, is there an ETA for a release with this fix in it?

**Comment by annawinkler** [comment]
I would also be interested to find out when this fix will be released - thank you! ✨

**Comment by sherifkayad** [comment]
@micahhausler ,

Is it possible to know when that fix will be available/when a new AMI is going to be available?

**Comment by tabern** [comment]
This will be in the marketplace-available optimized AMI with K8s version 1.11.8. See https://github.com/aws/containers-roadmap/issues/188

**Pull request merged**
