### PR TITLE
chore: fix versions script

### PR DESCRIPTION
**Pull request by bwagner5**
**Issue #, if available:**
n/a

**Description of changes:**
 - Fix versions file for cached images

Was showing like this:
```
  "images": [
    "602401143452.dkr.ecr.ap-south-2",
    "602401143452.dkr.ecr-fips.ap-south-2",
    "602401143452.dkr.ecr.us-west-2.amazonaws.com",
    "af-south-1",
    "ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-northeast-3",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ap-southeast-3",
    "ap-southeast-4",
    "ca-central-1",
    "eu-central-1",
    "eu-central-2",
    "eu-north-1",
    "eu-south-1",
    "eu-south-2",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "il-central-1",
    "me-central-1",
    "me-south-1",
    "sa-east-1",
    "us-east-1",
    "us-east-2.amazonaws.com",
    "us-west-1",
    "us-west-2"
  ]
```

now shows like this:

```
  "images": [
    "amazon-k8s-cni-init:v1.14.1",
    "amazon-k8s-cni-init:v1.14.1-eksbuild.1",
    "amazon-k8s-cni-init:v1.15.0-eksbuild.2",
    "amazon-k8s-cni:v1.14.1",
    "amazon-k8s-cni:v1.14.1-eksbuild.1",
    "amazon-k8s-cni:v1.15.0-eksbuild.2",
    "kube-proxy:v1.28.1-minimal",
    "kube-proxy:v1.28.1-minimal-eksbuild.1",
    "kube-proxy:v1.28.2-minimal-eksbuild.2",
    "pause:3.5"
  ]
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

### CODE REVIEW

**Comment by cartermckinnon** [comment]
So we can confirm things look as expected: https://github.com/awslabs/amazon-eks-ami/pull/1493

**Comment by cartermckinnon** [comment]
/ci build
+build cache_container_images=true

**Comment by cartermckinnon** [comment]
version info from CI looks fine to me (1.28):
```
"images":
    [
        "amazon-k8s-cni-init:v1.14.1",
        "amazon-k8s-cni-init:v1.14.1-eksbuild.1",
        "amazon-k8s-cni-init:v1.15.1",
        "amazon-k8s-cni-init:v1.15.1-eksbuild.1",
        "amazon-k8s-cni:v1.14.1",
        "amazon-k8s-cni:v1.14.1-eksbuild.1",
        "amazon-k8s-cni:v1.15.1",
        "amazon-k8s-cni:v1.15.1-eksbuild.1",
        "kube-proxy:v1.28.1-minimal",
        "kube-proxy:v1.28.1-minimal-eksbuild.1",
        "kube-proxy:v1.28.2-minimal-eksbuild.2",
        "pause:3.5"
    ]
```

@bwagner5 did something change in `ctr`'s output format? wondering what broke this

**Comment by bwagner5** [comment]
I'm not sure what broke this... I just noticed it when pulling version info from the latest AMI.

**Comment by cartermckinnon** [comment]
@bwagner5 I don't see this issue with HEAD, I'm wondering if your checkout just needed this fix: https://github.com/awslabs/amazon-eks-ami/pull/1461 ?

**Comment by bwagner5** [comment]
> @bwagner5 I don't see this issue with HEAD, I'm wondering if your checkout just needed this fix: #1461 ?

could be, if you're not seeing in HEAD I'll just close.

**Pull request closed without merging**
