### PR TITLE
Update eni-max-pods.txt

### PR DESCRIPTION
**Pull request by cartermckinnon**
*Description of changes:*

Update `eni-max-pods.txt` using the `generate-limits` target on [amazon-vpc-cni-k8s/Makefile](https://github.com/aws/amazon-vpc-cni-k8s/blob/f1728c5fd382ff31f2433a59ba09ce4ae1bb3c98/Makefile)

```sh
dev-dsk-mckdev-2b-f4db609f % make generate-limits
go run  scripts/gen_vpc_ip_limits.go
Adding "u-18tb1.metal": {15 50 unknown} since it is missing from the API
Adding "u-24tb1.metal": {15 50 unknown} since it is missing from the API
Adding "u-6tb1.metal": {5 30 unknown} since it is missing from the API
Adding "c5a.metal": {15 50 unknown} since it is missing from the API
Replacing API value {60 50 nitro} with override {15 50 unknown} for "p4d.24xlarge"
Replacing API value {60 50 nitro} with override {15 50 unknown} for "dl1.24xlarge"
Adding "cr1.8xlarge": {8 30 unknown} since it is missing from the API
Adding "hs1.8xlarge": {8 30 unknown} since it is missing from the API
Adding "c5ad.metal": {15 50 unknown} since it is missing from the API
Adding "u-12tb1.metal": {5 30 unknown} since it is missing from the API
Adding "u-9tb1.metal": {5 30 unknown} since it is missing from the API
{"level":"info","ts":"2022-02-03T21:54:42.312Z","caller":"/usr/lib/golang/src/runtime/proc.go:204","msg":"Generated pkg/awsutils/vpc_ip_resource_limit.go"}
{"level":"info","ts":"2022-02-03T21:54:42.314Z","caller":"/usr/lib/golang/src/runtime/proc.go:204","msg":"Generated misc/eni-max-pods.txt"}
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cartermckinnon** [comment]
This missed the `hpc6a.48xlarge` instance, because the output of `make generate-limits` is regionally-dependent. I was able to get the value for `hpc6a.48xlarge` with:
```sh
AWS_REGION=us-east-2 make generate-limits
```

It produced:
```
hpc6a.48xlarge 100
```

**Comment by cartermckinnon** [comment]
Should this script output the union of all regions' instance types? @suket22

**Comment by cartermckinnon** [comment]
> Can the same instance type support a different number of ENI's or IPs/ENI in different regions?

My tests indicate *no*, there was no disagreement about ENI count or IP per ENI count among the 17 default regions. I'll followup re: opt-in regions.

**Comment by cartermckinnon** [comment]
I opened a PR to update the script: https://github.com/aws/amazon-vpc-cni-k8s/pull/1846

**Review by abeer91 — APPROVED** [review]

**Pull request merged**
