### PR TITLE
Remove old kernels when upgrading.

### PR DESCRIPTION
**Pull request by cartermckinnon**
Some automated scanning tools may flag vulnerabilities in old kernels that are not actually in use.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mmerkes** [comment]
Did you test this out? Verify it builds and the old kernel is removed?

**Comment by cartermckinnon** [comment]
Second commit coming -- I missed adding `yum-utils`, which provides `package-cleanup` :)

**Comment by cartermckinnon** [comment]
I built a 1.19 AMI from this branch (`make 1.19`) and saw the 4.14 kernel get uninstalled during the build:
```
amazon-ebs: Loaded plugins: priorities, update-motd, versionlock
    amazon-ebs: --> Running transaction check
    amazon-ebs: ---> Package kernel.x86_64 0:4.14.275-207.503.amzn2 will be erased
    amazon-ebs: --> Finished Dependency Resolution
    amazon-ebs:
    amazon-ebs: Dependencies Resolved
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs:  Package      Arch         Version                        Repository       Size
    amazon-ebs: ================================================================================
    amazon-ebs: Removing:
    amazon-ebs:  kernel       x86_64       4.14.275-207.503.amzn2         installed       102 M
    amazon-ebs:
    amazon-ebs: Transaction Summary
    amazon-ebs: ================================================================================
    amazon-ebs: Remove  1 Package
    amazon-ebs:
    amazon-ebs: Installed size: 102 M
    amazon-ebs: Downloading packages:
    amazon-ebs: Running transaction check
    amazon-ebs: Running transaction test
    amazon-ebs: Transaction test succeeded
    amazon-ebs: Running transaction
    amazon-ebs:   Erasing    : kernel-4.14.275-207.503.amzn2.x86_64                         1/1
    amazon-ebs:   Verifying  : kernel-4.14.275-207.503.amzn2.x86_64                         1/1
    amazon-ebs:
    amazon-ebs: Removed:
    amazon-ebs:   kernel.x86_64 0:4.14.275-207.503.amzn2
    amazon-ebs:
    amazon-ebs: Complete!
```

**Comment by cartermckinnon** [comment]
The change was moved to `install-worker.sh`, because we need to do this cleanup *after* the instance reboots (you can't remove the currently-running kernel).

**Review by mmerkes — APPROVED** [review]
LGTM

**Pull request merged**
