### PR TITLE
Lint space errors

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Description of changes:**

Noticed we have some files with erroneous trailing spaces. This PR adds a check for them to `make lint`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cartermckinnon** [comment]
`lint` check failed, which is good! Pushing a revision that applies the formatting next.

**Comment by cartermckinnon** [comment]
`lint` check succeeded 👍

**Comment by mmerkes** [comment]
This is fine, but it there not a tool that just does the thing for you?

**Comment by cartermckinnon** [comment]
I could probably find *something* to pull in, but I'm not sure it'd be meaningfully better than `sed` for this purpose, and it'd just grow the BOM. Seems like this is usually a feature of text editors or language-specific linters, and we need something more flexible here.

**Comment by cartermckinnon** [comment]
Rebooting this PR. Updated the `lint` impl to use `git diff-tree` instead of `grep`. Fails as expected: https://github.com/awslabs/amazon-eks-ami/actions/runs/6563096967/job/17826538956?pr=1121

**Review by mmerkes — APPROVED** [review]
LGTM

**Pull request merged**
