### PR TITLE
Update new instance types

### PR DESCRIPTION
**Pull request by focaaby**
*Issue #, if available:*

*Description of changes:*

Update the new instance types

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dennisme** [comment]
Looks good +1

**Comment by 5p3c7r3** [comment]
+1

**Comment by treyhyde** [comment]
Looks like someone updated this upstream without accepting this PR.

**Comment by abeer91** [comment]
Hi, we ran the tool to regenerate the instance types again in case there were newer instance types. We'll be faster next time to review PRs.

**Comment by focaaby** [comment]
Hello @abeer91 

When will the commit https://github.com/awslabs/amazon-eks-ami/commit/548b1650e63f3ab582d79418c7b3336943642fd1 cherry-picks and release with new AMI version?

**Comment by DragonStuff** [comment]
Hey @abeer91,
Doesn't this actively block usage of `m6i` instances with EKS? I've got an open inquiry with AWS directly, but I'm keen to understand where this is currently blocked from the maintainer side.

We would really love to see the commit mentioned above released in the AMI so that we can benefit from it. If you have any information we would be grateful. Thank you!

**Comment by 5p3c7r3** [comment]
Anxiously awaiting the ability to jump onto the m6i instances as well. This is promising, what needs to happen next?

**Comment by dennisme** [comment]
https://github.com/awslabs/amazon-eks-ami/commit/548b1650e63f3ab582d79418c7b3336943642fd1 should have fixed it on the EKS AMI side. For the cni youd also want https://github.com/aws/amazon-vpc-cni-k8s/pull/1601 at least (release [1.9.1](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.9.1)

**Pull request closed without merging**
