### PR TITLE
Update to docker 25

### PR DESCRIPTION
**Pull request by Issacwww**
**Issue #, if available:**

**Description of changes:**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

build 1.24 AMI and verified docker version
`"docker": "25.0.3-1.amzn2.0.1"`

### CODE REVIEW

**Comment by cartermckinnon** [comment]
Let's hold on this for now

**Comment by cartermckinnon** [comment]
Package isn't available yet.

**Comment by ndbaker1** [comment]
/ci
+workflow:os_distros al2

**Comment by Issacwww** [comment]
/ci
+workflow:os_distros al2

**Comment by cartermckinnon** [comment]
Thank you for carrying this @Issacwww !

**Pull request merged**
