### PR TITLE
Add cri-tools

### PR DESCRIPTION
**Pull request by reegnz**
This allows using the crictl cli tool on worker nodes.

**Issue #, if available:**

#1486

**Description of changes:**

Installing cri-tools ensures that crictl is available on the worker nodes.
crictl is the official 1st party kubernetes tool to interact with the container runtime in a runtime-agnostic way.
It is also pod-aware so troubleshooting pods running on a node is made easier.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

Performed the same commands to install and configure crictl on a worker.
Running `crictl pods` and `crictl ps` works as expected.

### CODE REVIEW

**Comment by cartermckinnon** [comment]
There's more discussion in #1235.

The `cri-tools` README was updated since then to have more firm guidance around compatibility: https://github.com/kubernetes-sigs/cri-tools#compatibility-matrix-cri-tools--kubernetes

> It's recommended to use the same cri-tools and Kubernetes minor version, because new features added to the Container Runtime Interface (CRI) may not be fully supported if they diverge.

With k8s >= 1.27 needing cri-tools >= 1.27, and earlier k8s needing cri-tools <= 1.26.

So we can't just install the latest version of cri-tools from the AL repo. We also can't guarantee that the necessary version of cri-tools is available in the repo for current or future k8s versions.

**Comment by reegnz** [comment]
Nice catch @cartermckinnon , had that in the back of my mind but lost that by the time I opened the PR. 😅

Will adjust the logic to take that into consideration.

**Comment by reegnz** [comment]
So the package being installed currently is coming from the `amzn2-core` repository:
```
[root@ip-10-80-140-61 /]# yum --showduplicates list cri-tools | expand
Loaded plugins: priorities, update-motd, versionlock
Available Packages
cri-tools.x86_64                  1.25.0-1.amzn2.0.1                  amzn2-core
cri-tools.x86_64                  1.26.1-1.amzn2.0.1                  amzn2-core
cri-tools.x86_64                  1.26.1-1.amzn2.0.2                  amzn2-core
```

@cartermckinnon it seems like the amzn2-core repo doesn't provide a version for 1.27 and up. Could you please escalate to the amazon-linux team so they also package up the 1.27 version?

Alternatively, we could bring in google's repo, which has all versions of cri-tools available: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

As for version pinning, I'm not 100% familiar with how yum does it.

AFAICT you can install with `yum install cri-tools-1.26.1` but then you don't get updates if there's a hotfix. Alternatively you can `yum instl cri-tools < 1.27` but I'm unsure how it works with upgrades, although during AMI build it would likely always pick the latest version matching the constraint if that version is available.

**Comment by reegnz** [comment]
Ironically, the google yum repo also doesn't have a 1.27 package. 😅 
So I think this is a hard blocker to use cri-tools if nobody else has made any yum packages available either...

**Pull request closed without merging**
