### PR TITLE
Do not set KubeletCredentialProviders feature flag for 1.28+

### PR DESCRIPTION
**Pull request by camrakin**
**Issue #, if available:**

**Description of changes:**
1.28 test AMI builds are failing because KubeletCredentialProviders feature flag is no longer supported:
```
"command failed" err="failed to set feature gates from initial flags-based config: unrecognized feature gate: KubeletCredentialProviders"
```
This change removes KubeletCredentialProviders from featureFlags for 1.28, and adds the flag by version in the install-worker.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

Validated 1.28 AMI creation succeeds, and that conformance tests pass.
```
Plugin: e2e
Status: passed
Total: 7392
Passed: 169
Failed: 0
Skipped: 7223

Plugin: systemd-logs
Status: passed
Total: 3
Passed: 3
Failed: 0
Skipped: 0

Run Details:
API Server version: v1.28.0-rc.0-eks-caced21
Node health: 3/3 (100%)
Pods health: 14/14 (100%)
```

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

### CODE REVIEW

**Comment by cartermckinnon** [comment]
Can you add a unit test for this?

**Review by cartermckinnon — CHANGES_REQUESTED** [review]
Please add a unit test for this.

**Comment by camrakin** [comment]
Will do, working on that now. Should have a test added shortly

**Review by cartermckinnon — APPROVED** [review]

**Comment by cartermckinnon** [comment]
Discussed offline -- I hadn't noticed this change was in `install-worker.sh`, which isn't unit-testable in its current form, without current approach to unit tests. We've added things like this to `bootstrap.sh`, because it's more easily-tested, but I don't think that's enough of a reason to do one more thing at runtime versus build time.

**Pull request merged**
