### PR TITLE
feat(nodeadm): use cached kubelet version to reduce config time

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Issue #, if available:**

Improves #1751.

**Description of changes:**

This PR aims to reduce `nodeadm-config` time by determining the `kubelet` version using a text file created during the AMI build process, instead of executing `kubelet --version`.

Using `kubelet --version` involves EBS lazy-loading time plus the overhead of the child process, and doing this during `nodeadm-config` delays execution of the user's user data scripts and `nodeadm-run`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cartermckinnon** [comment]
Added a log for the execution time of `nodeadm init`, going to get a baseline:

/ci

**Comment by cartermckinnon** [comment]
Node logs are now collected for CI jobs: https://github.com/awslabs/amazon-eks-ami/pull/2010

/ci

**Comment by cartermckinnon** [comment]
Some timings from CI nodes (in seconds):
```
# 1.24
13.271587064 # m6i.large
13.167262858 # m6i.xlarge
12.91557005 # m6i.xlarge

# 1.31
13.311006288 # m6i.xlarge
13.572138308 # m6i.large
13.604205146 # m6i.large
```

**Comment by cartermckinnon** [comment]
Added `/etc/eks/kubelet-version.txt`, we'll see how much that improves the timings...

/ci

**Comment by cartermckinnon** [comment]
Timings when the `kubelet-version.txt` file is used (in seconds):
```
# 1.24
2.141777731 # m6i.xlarge
2.091775114 # m6i.xlarge
2.043645506 # m6i.xlarge

# 1.31
1.228009856 # m6i.xlarge
1.383285926 # m6i.xlarge
1.123423626 # m6i.xlarge
```

The variation in these samples seems to be due to the startup time of `containerd`, likely caused by EBS lazy-loading.

**Comment by cartermckinnon** [comment]
Definitely a nice improvement in `nodeadm-config` time:
| Kubernetes version | Reduction |
|--------|--------|
| 1.31 | 92.85% |
| 1.24 | 89.11% |

**Review by Issacwww — APPROVED** [review]
🚀

**Review by ndbaker1 — APPROVED** [review]
nice gains!

**Pull request merged**
