### PR TITLE
Update to `containerd` 1.7

### LINKED ISSUE #1503: Update to `containerd` 1.7.x
**What would you like to be added**:

We should update from 1.6.x to 1.7.x.

**Why is this needed**:

Eventually, the `--pod-infra-container-image` flag will be removed, and we'll require the pinned-image support in `containerd` 1.7 to avoid the sandbox image being garbage-collected.

- [Clean up dockershim flags in the kubelet](https://github.com/kubernetes/kubernetes/issues/106893)

### PR DESCRIPTION
**Pull request by cartermckinnon**
**Issue #, if available:**

Closes #1503 

**Description of changes:**

Update to `containerd` 1.7.x

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

*TODO*

### CODE REVIEW

**Comment by cartermckinnon** [comment]
Kicking off a fresh run before we merge.

/ci

**Review by mmerkes — APPROVED** [review]
Let's go!

**Pull request merged**
