### PR TITLE
AMI Release v20221104

### PR DESCRIPTION
**Pull request by cartermckinnon**

### CODE REVIEW

**Comment by anish** [comment]
@cartermckinnon fyi, makefile does not include 1.24 yet despite it being in the release notes https://github.com/awslabs/amazon-eks-ami/issues/1091

**Comment by cartermckinnon** [comment]
@anish yep, that PR is coming 😄

**Review by xr1776 — APPROVED** [review]

**Comment by anish** [comment]
@cartermckinnon issue was closed, but I don't see a PR yet

**Comment by cartermckinnon** [comment]
I expected the PR to be merged yesterday, but we're still tying up loose ends here related to 1.24 support. I expect it to be up today/tomorrow as we prepare for general availability of 1.24 on EKS.

**Pull request merged**
