### PR TITLE
Fixed --enable-docker-bridge bootstrap arg

### PR DESCRIPTION
**Pull request by micahhausler**
*Issue #, if available:*

Fixes bug introduced in #187 

*Description of changes:*

* Correctly set the docker bridge env var
* Safely write the docker config file

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by micahhausler** [comment]
FYI @0xAhmed @msvechla

**Comment by 0verc1ocker** [comment]
This is the dumbest bootstrapping process of kubelet I have seen yet. Congratulations.

**Comment by micahhausler** [comment]
> This is the dumbest bootstrapping process of kubelet I have seen yet. Congratulations.

@0verc1ocker is there something you’d like to see done differently?

Micah Hausler
Systems Development Engineer – EKS
Amazon Web Services

**Comment by 0verc1ocker** [comment]
> This is the dumbest bootstrapping process of kubelet I have seen yet. Congratulations.
> @0verc1ocker is there something you’d like to see done differently?

I'm sorry @micahhausler . It has been a frustrating day. :cry:  I just find it really confusing when arguments get passed from CloudFormation parameter into another script and then trying to figure out where things broke. In this sense, bootstrap.sh is acting as a single point of failure and it has multiple flags of where it can break.

My opnion is that allowing users to just append a startup script as a service, similar to `kops` hooks would be better experience overall if using CloudFormation to spin up the instances. Eventually they will have to use UserData for their own custom operations anyways.

**Comment by moshid** [comment]
Thank you for this fix! I'm new to eks, how do I apply the flag --enable-docker-bridge on an already running stack? I've used `jx create cluster eks` to create the cluster

**Pull request merged**
