### PR TITLE
Update container-runtime package versions

### LINKED ISSUE #800: Containerd v1.5 support?
**What would you like to be added**:

Update Containerd version to  v1.5
I did not find any roadmap or existing Issue on that so I wonder if this is something planned and what is the scope of the changes.

**Why is this needed**:

In particular for me the trigger to this question was this functionality added in 1.5 - https://github.com/containerd/containerd/blob/main/docs/hosts.md

### LINKED ISSUE #985: containerd image pulling performance
We have trouble with running our EKS clusters with containerd container runtime. When pods with huge images start creating at the same time on the same node - kubernetes nodes become unstable, all running pods on this node - freeze.

To reproduce:

1. you need image with huge amount of small files, or use my test image `paskalmaksim/stress-test-pulling-big-image:200k`
```
FROM ubuntu:latest

WORKDIR /app

RUN seq -w 1 200000 | xargs -n1 -P8 -I% sh -c 'dd if=/dev/urandom of=file.% bs=$(shuf -i1-5 -n1) count=1024' 2> /dev/null
```

2. you need a kubernetes node, our scenario: (m5.xlarge, 50GB, gp3, 3000iops, 125 throughput) . Drain node
```bash
kubectl drain <node name> --ignore-daemonsets --delete-emptydir-data
```

3. run pods with test image on this node
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test-pulling-big-image
  labels:
    app: stress-test-pulling-big-image
spec:
  strategy:
    type: Recreate
  replicas: 30
  selector:
    matchLabels:
      app: stress-test-pulling-big-image
  template:
    metadata:
      labels:
        app: stress-test-pulling-big-image
    spec:
      nodeSelector:
        kubernetes.io/hostname: <node name>
      tolerations:
      - effect: "NoSchedule"
        operator: "Exists"
      containers:
      - name: stress-test-pulling-big-image
        image: docker.io/paskalmaksim/stress-test-pulling-big-image:200k
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 10m
            memory: 10Mi
        command:
        - sleep
        - 1d
```

CPU and disk iops 100%

_Environment:_
kubernetes v1.22.9-eks-810597c
kernel 5.4.204-113.362.amzn2.x86_64
containerd://1.4.13

### PR DESCRIPTION
**Pull request by dewjam**
**Issue #, if available:**

Resolves #985, Closes #800

**Description of changes:**
Updates container-runtime packages to the most recent versions available in AL2 repos.
```
docker-20.10.17-1.amzn2
containerd-1.6.6-1.amzn2
runc-1.1.3-1.amzn2
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**
* Manually built AMIs for each K8S version/architecture
* Ran EKS conformance tests on all variations of AMIs:

|k8s version|arch|runtime|status|
|-|-|-|-|
|1.21|amd64|containerd-1.6.6|pass|
|1.22|amd64|containerd-1.6.6|pass|
|1.23|amd64|containerd-1.6.6|pass|
|1.21|arm64|containerd-1.6.6|pass|
|1.22|arm64|containerd-1.6.6|pass|
|1.23|arm64|containerd-1.6.6|pass|
|1.21|amd64|docker-20.10.17|pass|
|1.22|amd64|docker-20.10.17|pass|
|1.23|amd64|docker-20.10.17|pass|
|1.21|arm64|docker-20.10.17|pass|
|1.22|arm64|docker-20.10.17|pass|
|1.23|arm64|docker-20.10.17|pass|

### CODE REVIEW

**Comment by dewjam** [comment]
Looks like there is already a duplicate PR and issue out there for this.  #985  and #986 .

**Comment by cartermckinnon** [comment]
Thanks for putting this together -- we just need to verify that these package versions are also available in the partitions:
- `aws-cn`
- `aws-us-gov`

**Comment by dewjam** [comment]
Let me see if I can figure that out.  Thanks!

**Comment by dewjam** [comment]
OK, so for sure in aws-cn.

```
containerd.x86_64                      1.6.6-1.amzn2                  amzn2extra-docker
containerd-stress.x86_64               1.6.6-1.amzn2                  amzn2extra-docker
docker.x86_64                          20.10.17-1.amzn2               amzn2extra-docker
runc.x86_64                            1.1.3-1.amzn2                  amzn2extra-docker
```

**Review by prasad0896 — APPROVED** [review]

**Comment by cartermckinnon** [comment]
I verified `aws-us-gov`:
```
sudo yum list available | grep -e runc -e containerd -e docker
containerd.x86_64                      1.6.6-1.amzn2                  amzn2extra-docker
docker.x86_64                          20.10.17-1.amzn2               amzn2extra-docker
runc.x86_64                            1.1.3-1.amzn2                  amzn2extra-docker
```

We're good to go 👍

**Review by cartermckinnon — APPROVED** [review]

**Pull request merged**
