### PR TITLE
Support bootstrap env from file

### PR DESCRIPTION
**Pull request by stevehipwell**
https://github.com/awslabs/amazon-eks-ami/issues/844

*Description of changes:*

Support providing environment variables to _bootstrap.sh_ via an optional file (_/etc/profile.d/bootstrap-env.sh_) that is sourced if it exists. This solves the problem of no variable persistence between cloud-init steps which currently stops MNGs providing bootstrap overrides. To support adding `KUBELET_EXTRA_ARGS` to MNGs if  `KUBELET_EXTRA_ARGS` is set before the args are processed it will be persisted to  `KUBELET_EXTRA_ARGS_ENV` which will be appended to any value pass in via the args.

From non-MNG nodes this functionality can be used to add dynamic node labels based on instance metadata amongst other things.

This pattern has been in use for while with no issues, but this official change will make it safer as it removes the need to modify _bootstrap.sh_.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@cartermckinnon could you take a look at this please?

**Comment by suket22** [comment]
The alternative I've been thinking of is that the bootstrap script supports accepting two filePaths : one that points to the kubelet configuration, and one to the container runtime configuration. The latter now exists for [containerd](https://github.com/awslabs/amazon-eks-ami/pull/929).

If we were to re-write the bootstrapping in a different language / as a binary, it might be easier to continue to honor these configuration files rather than honoring *all* bash environment variables as defined in the original bootstrap script. 

I'm making an assumption here that overriding kubelet configuration, and container runtime configuration are the only use cases. I don't think most folks are looking to override the API Server endpoint / Cluster certificate etc. Having said that, if someone's looking to do that, they should probably just bootstrap the whole thing themselves.

**Comment by stevehipwell** [comment]
@suket22 I missed your second reply. Many people are making other changes such as adding custom CAs to the OS and adding OCI credentials to kubelet. The configuration options in Bottlerocket are a good starting point, but remember that it has init containers for the real edge cases; say dynamic node labels based on the subnet the node starts in.

**Comment by suket22** [comment]
> That said, I think you'll have to offer a switch between the new binary and old shell bootstrapping; so I don't think it matters if more work is done to the current logic as long as there is a way to do the same with the new binary

Agreed, I just don't know how we can offer the switch via the Managed Nodegroups API. I don't think we're going to be adding a new EKS API parameter for this. I think the best CX would be for us to switch over to a newer binary without anyone with an existing nodegroup having to change anything. 

> Many people are making other changes such as adding custom CAs to the OS and adding OCI credentials to kubelet

Fair point. I'd assume this is very niche though right? I think as a managed service we need to draw the line somewhere. At this level of customization, it probably makes sense to take complete ownership of the bootstrapping (like how custom AMIs + MNG does it).

**Comment by suket22** [comment]
Playing devil's advocate, there's no way enforce backwards compatibility regardless :(
If someone's using Managed Nodegroups and is editing the `/etc/eks/bootstrap.sh` file on disk directly in their MIME part, all their edits become useless if Managed Nodegroups starts calling a different binary. 
So maybe a switch is something we'd need regardless.

**Comment by cartermckinnon** [comment]
Closing along with #875 .

**Pull request closed without merging**
