### PR TITLE
add source_ami_filter_name to makefile PACKER_VARIABLES

### PR DESCRIPTION
**Pull request by agrahamlincoln**
*Issue #, if available:* #539 

*Description of changes:* add `source_ami_filter_name` to `PACKER_VARIABLES` in the Makefile

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mmerkes** [comment]
Sorry for the long delay. This looks reasonable to me. Update the PR so that it's mergeable and I'll approve.

**Comment by agrahamlincoln** [comment]
thanks @mmerkes ! I rebased to `master` and it looks mergeable now.

**Review by mmerkes — APPROVED** [review]
LGTM. I want to build an AMI with this to verify it works as expected and then I'll merge. Tx!

**Comment by mmerkes** [comment]
Verified this works.

Verified this uses the base selector:

```
make 1.19
```

Verified this uses a different selector:

```
k8s kubernetes_version=1.18.9 kubernetes_build_date=2020-11-02 pull_cni_from_github=true source_ami_filter_name=amzn2-ami-minimal-hvm-2017*
```

**Pull request merged**
