### PR TITLE
Skip installing amazon-ssm-agent if already present

### PR DESCRIPTION
**Pull request by pjaudiomv**
**Issue #, if available:**
#1500

**Description of changes:**
This skips installation of the amazon-ssm-agent if it is already installed on base AMI.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Testing Done**

*[See this guide for recommended testing for PRs.](../doc/CONTRIBUTING.md#testing-changes) Some tests may not apply. Completing tests and providing additional validation steps are not required, but it is recommended and may reduce review time and time to merge.*

### CODE REVIEW

**Comment by pjaudiomv** [comment]
@cartermckinnon  lint failed, just fixed and verified locally

**Comment by cartermckinnon** [comment]
Looks fine in the previous run, but I'll give it another go before we merge: https://github.com/awslabs/amazon-eks-ami/actions/runs/6726308376/job/18282323391#step:4:1410

/ci build

**Comment by cartermckinnon** [comment]
@pjaudiomv if you have a public source AMI that already has the agent installed, I can kick off a run with that for good measure.

**Comment by pjaudiomv** [comment]
> @pjaudiomv if you have a public source AMI that already has the agent installed, I can kick off a run with that for good measure.

Yea how about just using latest `amzn2-ami-hvm-*-x86_64-ebs` either `ami-01afe71195af3fd1d` for us-east-1 or `ami-07c6e12db62abb290` for us-gov-west-1

**Comment by cartermckinnon** [comment]
/ci build
+build source_ami_filter_name="amzn2-ami-hvm-*"

**Comment by cartermckinnon** [comment]
> 2023-11-02T00:19:26Z: Build 'amazon-ebs' errored after 3 seconds 649 milliseconds: Error launching source instance: InvalidBlockDeviceMapping: Volume of size 4GB is smaller than snapshot 'snap-01822afedf1b7d0d1', expect size >= 8GB

/ci build
+build source_ami_filter_name="amzn2-ami-hvm-*" launch_block_device_mappings_volume_size=8

**Comment by pjaudiomv** [comment]
are you able to pass in `launch_block_device_mappings_volume_size="8"` to CI otherwise i can make an ami off amzn2 with 8gb real quick

**Comment by cartermckinnon** [comment]
yup, we're good 👍 

https://github.com/awslabs/amazon-eks-ami/actions/runs/6726644564/job/18283267340#step:4:1102

**Review by cartermckinnon — APPROVED** [review]

**Comment by pjaudiomv** [comment]
Thanks @cartermckinnon  I appreciate your help and swift review.

**Pull request merged**
