### PR TITLE
Add new instance types

### PR DESCRIPTION
**Pull request by mogren**
*Description of changes:*

* Added a1, c5n, m5ad, r5ad

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mogren** [comment]
Updated based on https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#AvailableIpPerENI

Wait to merge until [CNI v1.4.0](https://github.com/aws/amazon-vpc-cni-k8s/milestone/5) is out.

**Comment by JoshuaOnScale** [comment]
CNI 1.3.2 supports c5n. Is there something else blocking this?

**Comment by mogren** [comment]
Support added in https://github.com/aws/amazon-vpc-cni-k8s/pull/459

Will be out in [v1.5](https://github.com/aws/amazon-vpc-cni-k8s/milestone/6)

**Comment by mogren** [comment]
@micahhausler v1.4.1 has all except t3a, v1.5.0 will support all of these types.

**Comment by JoshuaOnScale** [comment]
Do the latest published AMIs found [here](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) have C5N support? The node yaml still does not contain that type on the list.

**Pull request merged**
